name: places_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.1.3
homepage: https://github.com/drexsoftorg/places_picker
issue_tracker: https://github.com/drexsoftorg/places_picker/issues
repository: https://github.com/drexsoftorg/places_picker

platforms:
  android:
  ios:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_api_headers: ^1.5.0+1
  tuple: ^2.0.1
  http: ^0.13.5
  cirilica: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

screenshots:
  - screenshot2.png

assets:
  - assets/styles/
